// Generated by typings
// Source: 
// Type definitions for livereload
// Project: https://github.com/napcs/node-livereload
// Definitions by: Jussi Kinnula <https://github.com/jussikinnula/>
// Definitions: https://github.com/jussikinnula/DefinitelyTyped

declare module 'livereload' {
    import * as http from "http";
    export function createServer(): http.Server;
    export function watch(path: string): any;
}